### ISSUE TITLE
A problem I met when detectron2 being installed 

### ISSUE THREAD

**Issue by cxy9906** [ezeli/BUTD_model#4]
When I installed the detectron2 version in read-me, the following error message appeared. But it will not appear when downloading the latest detectron2 version. However, the latest version is the same as the author said, an error will occur when running the demo for extracting features（new_extract_features）.Hope to get the author's answer, thank you.

   /home/wwy/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wwy/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract/detectron2/setup.py'"'"'; __file__='"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract/detectron2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by cxy9906** [comment]
Hello, after I installed the ninja package, the previous problem did not appear, but a new problem appeared as follows:

   ninja: build stopped: subcommand failed.
.......
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wwy/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract-master/detectron2/setup.py'"'"'; __file__='"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract-master/detectron2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.


**According to the prompt in the first line, after searching, I downgraded torch (originally 1.8.0), and new problems appeared as follows:**
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract-master/detectron2/setup.py", line 115, in <module>
        setup(
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/wwy/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/wwy/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in build_extensions
        build_ext.build_extensions(self)
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/wwy/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/wwy/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/wwy/anaconda3/lib/python3.8/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 288, in unix_wrap_compile
        "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
      File "/home/wwy/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1027, in _get_cuda_arch_flags
        raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
    ValueError: Unknown CUDA arch (8.6) or GPU not supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wwy/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract-master/detectron2/setup.py'"'"'; __file__='"'"'/home/wwy/PycharmProjects/pythonProject/bottom_up_features_extract-master/detectron2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by ezeli** [comment]
You can follow the original project [MILVLG/bottom-up-attention.pytorch](https://github.com/MILVLG/bottom-up-attention.pytorch). I just added a new file `new_extract_features.py` and modified the feature storage format.
